#!/usr/bin/env bash
# a Bash script that will display information about subdomains

dom_info () {
	line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -1)
	echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ "$#" == 1 ]
then
	dom_info "$1" "www"
	dom_info "$1" "lb-01"
	dom_info "$1" "web-01"
	dom_info "$1" "web-02"
elif [ "$#" == 2 ]
then
	dom_info "$1" "$2"
fi
