#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header

NEW_RULE="\\\tadd_header X-Served-By $(hostname);\n"
sudo sed -i "24i $NEW_RULE" /etc/nginx/sites-available/default
sudo systemctl reload nginx
