#!/usr/bin/env bash
# Configure haproxy to distribute traffic to 2 servers

apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
apt-get -y install haproxy=1.6.\*

echo='
frontend ghaly.tech
    bind 0:80
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 283427-web-01 100.25.36.194:80 check
    server 283427-web-02 54.89.117.225:80 check
'  >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
