#!/usr/bin/env bash
# Configure haproxy to distribute traffic to 2 servers

commando="\
frontend http
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 283427-web-01 100.25.36.194:80 check
    server 283427-web-02 54.89.117.225:80 check
"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install haproxy=2.0.\*
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$commando" >> /etc/haproxy/haproxy.cfg
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo service haproxy restart
