#!/usr/bin/env bash
# a Bash script that configures a server to listen on port 80

sudo sed -i '21 s/8080/80/' /etc/nginx/sites-enabled/default
sudo sed -i '22 s/8080/80/' /etc/nginx/sites-enabled/default
sudo service nginx restart
