#!/usr/bin/env bash
# prints a sentence every 2 seconds indefinitely
# prints I am invincible!!! when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM
while true
do
  echo "To infinity and beyond"
  sleep 2
done
