#!/usr/bin/env bash
# This script is displaying fizzbuzz famous sequence 

for num in {1..100}
do
  if (( num % 5 == 0 ))
  then
    if (( num % 3 == 0 ))
    then
	echo "FizzBuzz"
	continue
    else
      echo "Buzz"
      continue
    fi
  fi
	if (( num % 3 == 0 ))
	then
		echo "Fizz"
		continue
	else
		echo "$num"
	fi
done
