#!/usr/bin/env bash
# This script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

members=$(ls)
for member in $members
do
  echo "$member" | cut -d '-' -f2
done
