#!/usr/bin/env bash
# script that configures the container to run nginx on nginx user in 7 lines
pkill -f apache2
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo sed -i "1i user nginx;" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
